sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t paul311/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true paul311/docker-react npm run test
